language: python
python:
  - "3.6"
cache: pip
install:
  # This is actually totally unecessary, but if I don't add it, Travis attempts
  # to install the contents of "requirements.txt", which of course does not
  # exist. There's probably a better way..
  - return 0
script:
  - travis/build_archives.sh
deploy:
  # Deploy the CloudWatch script
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "rs-cos-assets"
  skip_cleanup: true
  local_dir: builds/ec2
  upload-dir: ec2
env:
  global:
  - secure: z91myPMgnToAMvVwBP8d3MVwLiTVCy7eCxj+8pOk+ldx2ybPKZvQhmBMNKLc0rx7Frb5Ycuwvx0ssd33FoPvKN3RhozgLHByEhomUj5jvqFqLlnvgNCoJ6oalEpThQXsdPlm4vUJ9DWytWNSDWJ06Et0xZeDFykM2te0TS68x1BmS4RXdKuouwvxuESfBalwU+hCGTVMuRD0+4F7IuDV+9u/2lIFKpyYauTpuLPAZORIbuaS93yXxYPvlKIuCUByjKidVPdAQnzFU1iVzIqSTSLqSoyL1ahdeiEbyaz24VYfmA6VHYWXwjD8JfzaLQDSJUUIT/Rq7kDPZbVr7sDSW1PgkobV/rtAXfsGPEACAXY5jcuUW5LzdM7VRwPwjRhm5T3DVz+p9s0y4+twpwY5x7BiwgvnpEJDrAksEu7FA1cniLRtvnx4psrAfGj9dFoXgqEeS+VJivYfrWWUpHZiJEmNaiRlQd0uhP6j66DN/iDnmIfQVyah2XYyF2l/PN5tTLdcS1P9e2Wwb+iwGjvHkId5cB+OJvaE6TU27Uxazx5NTn1P8SjOClX+LzzUBvu1/4gNvYMOVN8NeghVfjyLL6OEalawGps0pYIDSKvWnZns46nffYjOnwZTUzmsBYyz8jeA8KDgITd1jRtLUQt6XeyyLobkjgIV7lSZs7DxHMQ=
  - secure: h1k1iUYPpcQTcXp4RFTMHxTw7VpI5wmIFTd0xrWCd3rGovwC0k1KVUcG0bBp0mntpXFSWZ9sshkn2YAuIDSFu0F1VtTqIyMpAf9Wtmb38Xm91hTvw3DaWBZ86CtLGLBvf2ZFutcwPe1s3rWQzGPXQYqs3yyBkji0ZSKHWmuhp/2Dk3m/QLGFkZodswuGOFVLfyDFRtXCtIbImE48UOPg73Uv5bRTdYkXwzRApeCuYPFusG5c2cbDuRjX9PBGu4BOrFEQoij70UsYislQShjWMounnngwA+/1EsLJA443EYlB4LIym0Hdxbf0NQSCc2SwOOUtL+m4BXtj7Y0t5zZ8aCGRutRA/v+DP0Sh6rfQWfdcrdupRKjOmJms0t5qQ4IoImTQpgJIw4U9Q94XYtQlIEV8iXobZL9ro1rV/+kZEiu2g82CsMjGqU2rYtORETWg8BjCSqu4TzXOBnJDxaAXFPhMF3mBNUcGlIBT0ch9UwX1YB8voCVSS8ca+4WvdMWLZCTV9VKq2hUU/67CoVATc47csD/3QEPf+qa+EHMBYUTVwHXfzqkTnvUr6lnlPExomUuA8DQaZi5FgHfzdO6+ax1EKZDQ/pJAO1GI2DRJQ7TttPKZmPFqBu7UY140YmTHrG4+A5ofiWJckgHpIPe2oz5JdGCvcvN7Z9KIzbzvIHE=
